import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 11.0

[font.normal]
family = "FiraCode Nerd Font"

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
startup_mode = "Maximized"
dynamic_padding = false
opacity = 0.95
blur = true

[window.padding]
x = 10
y = 10
