require("config.lazy")
require("config.autocmd")

require("config.colorscheme")
require("config.conform")
require("config.keymaps")
require("config.fzf")
require("config.treesitter")
require("config.vim")
require("config.parrot")
require("config.cmp")
require("config.lsp")
